version: '3.7'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  # PROMETHEUS
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000